import Head from "next/head";
import Image from "next/image";
import { useContext } from "react";
import AddAddress from "../components/AddAddress";
import AddressBook from "../components/AddressBook";
import ConnectWallet from "../components/ConnectWallet";
import EthersContext from "../context/ethers-context";
import styles from "../styles/Home.module.css";

export default function Home() {
  const ethersCtx = useContext(EthersContext);
  return (
    <div className={styles.container}>
      <Head>
        <title>Address Book dApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ConnectWallet />
      <main className={styles.main}>
        {ethersCtx.contract ? (
          <h2>📔 Address Book of {ethersCtx.userAddress}</h2>
        ) : (
          <div className={styles.intro}>
            <h1>📔 Address Book dApp </h1>
            <h3>Connect your wallet to Start :)</h3>
          </div>
        )}
        {ethersCtx.contract ? <AddAddress /> : null}
        {ethersCtx.contract ? <AddressBook /> : null}
      </main>
    </div>
  );
}
