import Head from "next/head";
import Image from "next/image";
import { useContext } from "react";
import AddAddress from "../components/AddAddress";
import AddressBook from "../components/AddressBook";
import ConnectWallet from "../components/ConnectWallet";
import EthersContext from "../context/ethers-context";
import styles from "../styles/Home.module.css";

export default function Home() {
  const ethersCtx = useContext(EthersContext);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ConnectWallet />
      <main className={styles.main}>
        <AddAddress />
        {ethersCtx.contract ? <AddressBook /> : null}
      </main>
    </div>
  );
}
