import Head from "next/head";
import Image from "next/image";
import Connect from "../components/Connect";
import ConnectWallet from "../components/ConnectWallet";
import EthersWallet from "../components/EthersWallet";
import GameDetails from "../components/GameDetails";
import styles from "../styles/Home.module.css";
import { useContext } from "react";
import EthersContext from "../context/ethers-context";

export default function Home() {
  const ethersCtx = useContext(EthersContext);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <EthersWallet />
        {ethersCtx.contract && <GameDetails />}
        <p>Tester</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
